name: Fadlc
description: Finally a Decent Land Claim
author: Preva1l
version: '${version}'
main: info.preva1l.fadlc.Fadlc
api-version: 1.16

libraries:
  - redis.clients:jedis:5.1.0
  - org.apache.commons:commons-pool2:2.12.0
  - org.mongodb:mongodb-driver-sync:5.0.0
  - org.xerial:sqlite-jdbc:3.45.2.0
  - com.mysql:mysql-connector-j:8.3.0
  - org.mariadb.jdbc:mariadb-java-client:3.3.3
  - net.kyori:adventure-text-minimessage:4.17.0
  - net.kyori:adventure-api:4.17.0
  - net.kyori:adventure-platform-bukkit:4.3.3
  - com.influxdb:influxdb-client-java:3.3.0

permissions:
  fadlc.claim:
    default: true